site_name: Lind-Wasm Docs
site_url: https://lind-project.github.io/lind-wasm-docs/
theme:
  material

nav:
  - Home: index.md
  - Internal Documentation:
    - libc: internal/libc.md
    - Wasmtime: internal/wasmtime.md
    - RawPOSIX: internal/rawposix.md
    - Multi-Processing: internal/multiprocess-support.md
  - Build System:
    - Building libc: build/build-libc.md
    - Building wasmtime: build/build-wasmtime.md
    - Building RawPOSIX: build/build-rawposix.md
    - Bazel: build/bazel.md
  - Usage:
    - Compile Programs: use/compile-programs.md
    - Debug Programs: use/debug-programs.md
    - Run Programs: use/run-programs.md
    - Examples: use/examples.md
  - Contributing:
    - contribute/README.md
    - Rust style guide: contribute/styleguide.md
    - Unit tests: contribute/unit-tests.md
    - Adding to the docs: contribute/writeDoc.md
  - More:
    - Maintainers: more/maintainers.md
  - Community: community.md


  # - Progress: daily.md
  # - WASM Knowledge:
  #   - understandTls.md
  # - Building WASM glibc: buildGlibcWASM.md
  # - Compile safeposix-rust: compile-safeposix-rust.md
  # - Compiling Wasmtime from Source: compile-wasmtime.md
  # - Compiling C to WASM: wasmCompile.md
  # - Debugging WASM module with Wasmtime: wasmtime-debug.md
  # - How to add docs: writeDoc.md
  # - Team: team.md

extra_css:
  - stylesheets/img.css
