site_name: Lind-Wasm Docs
site_url: https://lind-project.github.io/lind-wasm-docs/
theme:
  material

nav:
  - Home: index.md
  - Using Lind-Wasm:
    - Compiling programs: use/compile-programs.md
    - Running programs: use/run-programs.md
    - Debugging programs: use/debug-programs.md
  - Internal Documentation:
    - libc: internal/libc.md
    - Wasmtime: internal/wasmtime.md
    - RawPOSIX: internal/rawposix.md
    - Multi-Processing: internal/multiprocess-support.md
    - Memory: internal/vmmap.md
  - Build System:
    - Building libc: build/build-libc.md
    - Building wasmtime: build/build-wasmtime.md
    - Building RawPOSIX: build/build-rawposix.md
    - Bazel: build/bazel.md
  - Testing:
    - Unit tests: testing/unit-tests.md
  - More:
    - Our Team: more/team.md
    - Adding to the docs: more/writeDoc.md
  



  # - Progress: daily.md
  # - WASM Knowledge:
  #   - understandTls.md
  # - Building WASM glibc: buildGlibcWASM.md
  # - Compile safeposix-rust: compile-safeposix-rust.md
  # - Compiling Wasmtime from Source: compile-wasmtime.md
  # - Compiling C to WASM: wasmCompile.md
  # - Debugging WASM module with Wasmtime: wasmtime-debug.md
  # - How to add docs: writeDoc.md
  # - Team: team.md

extra_css:
  - stylesheets/img.css
